default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  reconnect: true
  encoding: utf8
  username:
  password:

development:
  <<: *default
  host: ''
  database: url_shortner_development

test:
  <<: *default
  database: url_shortner_test

production:
  <<: *default
  database: url_shortner_production
